### ISSUE TITLE
DIAMOND file

### ISSUE THREAD

**Issue by ilaydagulmez** [almeidasilvaf/doubletrouble#5]
Hi again, after a long time break I came back to great tool :)

My question is about DIAMOND blast file. Here is my file looks like:

<img width="721" alt="Ekran Resmi 2024-08-02 15 23 01" src="https://github.com/user-attachments/assets/96613cb0-f641-41a7-aba4-acddd18e9e87">

When I tried the command
```
 c_binary <- classify_gene_pairs(
  annotation = pdata$annotation,
  blast_list = blast_data_list,
  scheme = "binary"
)

```
I got the fail like this even _seq_, _annotation_ and _diamond_ names are same:

<img width="631" alt="Ekran Resmi 2024-08-02 12 26 03" src="https://github.com/user-attachments/assets/9f0f6e19-dad4-4a5e-a8e6-513dc2ea7963">

Exited about final step to analysis :)

Thanks for your help and time,

Best

**Comment by almeidasilvaf** [comment]
Hi, @ilaydagulmez 

It seems like you didn't run DIAMOND with `syntenet::run_diamond()`, so your DIAMOND table doesn't have species IDs in front of gene IDs. If you look at gene IDs in your `pdata` object, you will notice that gene IDs have species identifiers. This is how __doubletrouble__ (and __syntenet__) match gene IDs across different objects when multiple species are present.

To solve this, you could:
1. See the species IDs in `pdata` (e.g., `head(names(pdata$seq)))`) and add them to columns 1 and 2 of your DIAMOND table; or
2. Re-run DIAMOND with `syntenet::run_diamond()`. DIAMOND searches are relatively quick to run (typically seconds or a few minutes max), so re-running them shouldn't be a problem.

Best,
Fabricio

**Comment by ilaydagulmez** [comment]
Hi, 
Thanks for your advice.

For first advice, the names of `pdata$seq` is "20628_1". I added the column 1-2 (but when all the names are same how it's will be read successfully?) like this: 


![WhatsApp Image 2024-08-05 at 15 36 37](https://github.com/user-attachments/assets/d24e836d-02be-4977-8e10-963fcaaeccbc)

Then I tried the c_binary with this data, but unfortunately I got the same error.

For this "Re-run DIAMOND with` syntenet::run_diamond()`" may I use the Herper env? I ask this cause of I've tried this easy way to create a DIAMOND file but I couldn't install DIAMOND with Herper.

![WhatsApp Image 2024-08-02 at 11 45 28](https://github.com/user-attachments/assets/da8054f0-bb46-44a4-9ac7-faf3ae088069)

![WhatsApp Image 2024-08-02 at 11 17 08](https://github.com/user-attachments/assets/0bf7bd08-fa82-4e5d-aae7-4bd098d5d7e8)

Cause when I try` syntenet::run_diamond()` I got the error:
> syntenet::run_diamond(
+   seq = pdata$seq["20628_1"],
+   compare = "intraspecies", 
+   outdir = file.path(tempdir(), "diamond_intra"),
+   ... = "--sensitive"
+ )
**Error in syntenet::run_diamond(seq = pdata$seq["20628_1"], compare = "intraspecies",  : 
  Unable to find DIAMOND in PATH.**

**Comment by almeidasilvaf** [comment]
Hi,

You replaced your gene IDs in your DIAMOND table with species IDs, when you should have appended species IDs to gene names. For example, if your species ID is "spp" and your gene ID is "gene1", the gene name should be "spp_gene1".

Again, I'd strongly recommend running DIAMOND again. It seems like your DIAMOND installation with Herper is not working properly (maybe an installation problem with the Conda environment?), so I would recommend installing DIAMOND in your machine. Here you can find instructions on how to do it:

1. Download DIAMOND binary: https://github.com/bbuchfink/diamond/wiki
2. You should move the DIAMOND binary to a directory that is in your R PATH. To see which directories are in your R PATH, run `r Sys.getenv("PATH")` in your R session. If your DIAMOND binary is in a directory that is not in your PATH, you can add such directory to your PATH by following instructions here: https://almeidasilvaf.github.io/syntenet/articles/syntenet.html#how-do-i-execute-an-external-dependency-that-is-not-in-my-path


Best,
Fabricio

**Comment by ilaydagulmez** [comment]
Hi, 
For the your first advice, even I changed the names I got the same error:

![image](https://github.com/user-attachments/assets/c661496f-353d-4046-945c-5d6f491804df)
![image](https://github.com/user-attachments/assets/2ee2fe51-8f1b-44c6-8979-7ac500c4d983)

For the second advice, I've tried to solve install DIAMOND, and it is still not working. I'm using MacOS and I've stuck the Linux MacOS incompatibility error

**Comment by almeidasilvaf** [comment]
Hi, @ilaydagulmez 

It might be that your problem comes from the fact that species IDs are numbers, not characters (species names). 

Could you try to replace the name of your lists (seq and annotation) with characters (e.g., "speciesname") and run it again? You'd have to:

1. Replace the names of the list elements in your `seq` and `annot` objects with something like "speciesname" or "species_name".
2. Run `syntenet::process_input()` with these 2 updated objects.
3. Inspect the `seq` element from the output list of `syntenet::process_input()` to see what species ID was used. **This should be an ID from 3-5 characters**.
4. Manually append the ID you found in step 3 to gene IDs in columns 1 and 2 of your DIAMOND table.

After this, I believe `classify_gene_pairs()` should work. Let me know if that solves your problem. If it does, I will modify the code of `syntenet::process_input()` to return an error if the list names start with numbers.

Best,
Fabricio

**Comment by ilaydagulmez** [comment]
Hi, thanks for the help.

I changed the names to "P_vul" but unfortunately got the same error unfortunately. 

Example lines:

> pdata$annotation
$P_vul
GRanges object with 105302 ranges and 1 metadata column:
                seqnames      ranges strand |           gene
                   <Rle>   <IRanges>  <Rle> |    <character>
       [1] P_v_scaffold1   1166-4860      + |      P_v_g1.t1

> pdata$seq
$P_vul
AAStringSet object of length 105302:
         width seq                                names               
     [1]   673 MWEGCKYSELQTAVKL...FYVPYPDQSRRDLAE P_v_g1.t1

> diamond_table
$P_vul
       query             db perc_identity length mismatches gap_open
1  P_v_g1.t1  P_v_g17823.t1          57.8    749        127       12

**Comment by almeidasilvaf** [comment]
Hi, 

Could you try not adding underscores? Just plain "Pvul".

**Comment by ilaydagulmez** [comment]
Hi,

Not working, unfortunately. The same error even when I try just "P" for the name. Example lines:

> pdata$annotation
$Pvul
GRanges object with 105302 ranges and 1 metadata column:
                seqnames      ranges strand |           gene
                   <Rle>   <IRanges>  <Rle> |    <character>
       [1] Pvu_scaffold1   1166-4860      + |      Pvu_g1.t1

> pdata$seq
$Pvul
AAStringSet object of length 105302:
         width seq                                                       names               
     [1]   673 MWEGCKYSELQTAVKLLTIKSDGGCVQ...DPFVIAQVASLVFYVPYPDQSRRDLAE Pvu_g1.t1

> diamond_blast
$Pvul
       query             db perc_identity length mismatches gap_open qstart qend tstart tend
1  Pvu_g1.t1  Pvu_g17823.t1          57.8    749        127       12      2  673      1  637

**Comment by almeidasilvaf** [comment]
Hi,

Could you send me your FASTA and GFF files, please? I will inspect this issue further to see what is happening.

Best,
Fabricio

**Comment by ilaydagulmez** [comment]
Hi, thanks for your time

For FASTA file: https://www.transfernow.net/dl/20240812WfiflYJ6

For GFF file: https://www.transfernow.net/dl/20240812zLGxVoAi

Hope you can access it without any problems.

Best,

İlayda

**Comment by almeidasilvaf** [comment]
Hi,

Everything worked well on my laptop, so there's no bug in the package. Without seeing all your code, I can't figure out what exactly went wrong in your analysis. You might be using an older version of the package or even an older version of R. I'm using R 4.4.1, and __doubletrouble__ 1.4.1.

Here is all the code I used:

```r
# Load packages
library(doubletrouble)
library(syntenet)

# Read files
seq <- list(Pvu = Biostrings::readAAStringSet("~/Downloads/P.fa"))
annot <- list(Pvu = rtracklayer::import("~/Downloads/P.gff"))

# Process data
pdata <- process_input(seq, annot)

# Run DIAMOND
diamond_intra <- run_diamond(
    seq = pdata$seq,
    compare = "intraspecies",
    ... = "--sensitive"
)

# Classify gene pairs and genes using the 'binary' scheme
cpairs <- classify_gene_pairs(
    annotation = pdata$annotation,
    blast_list = diamond_intra,
    scheme = "standard"
)
```

Some important notes:
1. I noticed that you have **a lot** of genes (over 100k). I am not sure if that's simply because you're working on a species with an oddly large number of genes, or if there's something wrong with your files. It's important to keep in mind that you should only use **one sequence per gene** - the translated sequence of the largest transcript -, so multiple isoforms per gene cannot be used.
2. It took a long time for `classify_gene_pairs()` to run (over 3 minutes, while it usually takes just a few seconds). I don't know why that happened, but it might suggest some issue with the data.
3. Originally, you were using the 'binary' scheme, but it turns out that your genome doesn't have any syntenic regions, so all duplicated gene pairs derived from small-scale duplications. Because of that, I re-ran it using the 'standard' scheme, so you get a more meaningful result (including subcategories of small-scale duplications).

I've attached a .tsv file with your classified duplicate pairs, in case you find them useful. FYI, this is your number of gene pairs per duplication mode:

```r
table(cpairs$Pvu$type)
#>    SD     TD     PD     DD 
#>     0    199     34 271196 
```

Best,
Fabricio

[classified_pairs_standard.tsv.gz](https://github.com/user-attachments/files/16582777/classified_pairs_standard.tsv.gz)

**Comment by ilaydagulmez** [comment]
Hi,

Thank you so much for your time and suggestions. My main issue is running `diamond` now. As we talked I had two options and one of them was using a `diamond` table which I got from Linux, and clearly, it's not working.

Another option is to run `diamond` with `syntenet`. Now I'm working on installing `diamond` and giving it R path for the final step. This option is the right way I think, like your pipeline.

My data belongs to tetraploid species and I think that's why so complicated. If I succeed `doubletrouble` for once, I will try to filter the gene prediction file.

Many thanks again,

Best,

İlayda

**Comment by almeidasilvaf** [comment]
Hi,

If your species is a tetraploid, I believe there's something problematic in your assembly or annotation or both. For tetraploids, you would expect to find a large fraction of the genome present in multiple copies (i.e., syntenic regions, with the same gene content and order). The fact that you don't find it (based on the analyses I ran) already triggers a warning.

On the DIAMOND docs, they mention that it can be installed from Homebrew on macOS laptops. In any case, if you need instructions on how to run DIAMOND on the command line and read its output to R, [this FAQ item](https://almeidasilvaf.github.io/syntenet/articles/syntenet.html#can-i-run-the-diamond-searches-on-the-command-line-and-import-the-results) can be helpful.

I will close this issue, then.

Best,
Fabricio
